using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Splines;
using BlockShooter.SodaConveyor;

namespace BlockShooter
{
    /// <summary>
    /// Marks a GameObject as generated by MacaronLevel.SyncGateMounts so the sync pass
    /// can clean up after itself without touching hand-placed children.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class GeneratedGateMount : MonoBehaviour
    {
        public int gateIndex = -1;
        public int slotIndex = -1;
    }

    [DisallowMultipleComponent]
    public sealed class MacaronLevel : MonoBehaviour
    {
        public enum PuzzleStyle { Automatic, Original, ClearLayers, ColorChains, BigOrders }
        [Header("Stage puzzle")]
        [Tooltip("Automatic: stage 1 stays original; later stages cycle Clear Layers, Color Chains and Big Orders.")]
        public PuzzleStyle puzzleStyle = PuzzleStyle.Automatic;
        public PuzzleStyle ResolvePuzzleStyle(int stage) => puzzleStyle != PuzzleStyle.Automatic ? puzzleStyle
            : stage <= 1 ? PuzzleStyle.Original : (PuzzleStyle)((stage - 2) % 3 + (int)PuzzleStyle.ClearLayers);

        public enum ConveyorShape
        {
            Automatic = 0,
            ConveyorTest_00 = 1, ConveyorTest_01, ConveyorTest_02, ConveyorTest_03, ConveyorTest_04,
            ConveyorTest_05, ConveyorTest_06, ConveyorTest_07, ConveyorTest_08, ConveyorTest_09
        }

        [Header("Soda Shippers level conveyor")]
        [Tooltip("Select the matching ConveyorTestScene layout and its supply. Automatic keeps the stage sequence.")]
        public ConveyorShape conveyorShape = ConveyorShape.Automatic;
        [Tooltip("Macarons across each conveyor row. Supported values are 2 and 4.")]
        public int conveyorLaneCount = 4;
        [Tooltip("Visual scale of conveyor macarons. Set per level prefab.")]
        [Min(.1f)] public float conveyorMacaronScale = 2f;
        [Tooltip("Total conveyor width in world units. Increase this to make the belt wider in the level preview and gameplay.")]
        [Min(.9f)] public float conveyorWidth = .9f;
        [Tooltip("Visible vertical gap between the tray pile and waiting slots, as a fraction of camera height.")]
        [Range(.005f, .06f)] public float waitingSlotScreenGap = .015f;

        public bool overrideCakeSupply;
        [Range(1, 9)] public int colorCount = 6;
        [Min(4)] public int cakeCount = 320;

        public enum TrayLayoutStyle { Compact = 0, Rectangle = 1, Diamond = 2, Pyramid = 3 }

        [Header("Tray layout")]
        [Tooltip("Compact keeps the mixed pile. Rectangle and Diamond arrange flat layouts; Pyramid stacks rectangular layers and shrinks each upper tier by 10%. Preview updates immediately.")]
        public TrayLayoutStyle trayLayoutStyle = TrayLayoutStyle.Compact;

        [Header("Tray difficulty")]
        [Tooltip("Shuffle colors only between equal-capacity trays, preserving every color's cake total.")]
        public bool shuffleTrayColors = true;
        [Tooltip("Seed for tray colors, mystery selection and tray scatter. Retry keeps the same arrangement.")]
        public int trayArrangementSeed = 1;
        [Tooltip("Local X/Z offset of alternate repeated stack tiers. Zero keeps authored alignment.")]
        public Vector2 repeatedTierOffset = new Vector2(.12f, .08f);
        [Tooltip("Fraction of ALL trays to hide, capped by how many are initially covered. 0 disables mystery trays.")]
        [Range(0, 1)] public float mysteryTrayRatio = .5f;
        public Color mysteryTrayColor = new Color(.55f, .55f, .58f);
        [Min(.01f)] public float mysteryRevealDuration = .35f;
        [Range(1, 1.2f)] public float mysteryRevealScale = 1.08f;

        public int ResolveConveyorStage(int stage) => conveyorShape != ConveyorShape.Automatic
            ? Mathf.Clamp((int)conveyorShape, 1, 10)
            : stage <= 10 ? Mathf.Max(1, stage) : new System.Random(stage).Next(3, 11);

        public StageGroupSpec[] BuildConveyorSupply(int sourceStage,
            out StageGroupSpec[] main, out StageBranchSpec[] branches)
        {
            if (conveyorLaneCount != 2 && conveyorLaneCount != 4)
                throw new InvalidOperationException($"{name}: Conveyor Lane Count must be 2 or 4.");
            int preset = sourceStage - 1;
            main = StageLayout.MainGroups(preset);
            branches = StageLayout.Branches(preset, sourceStage <= 3 ? 1f : sourceStage <= 7 ? 1.25f : 1.5f,
                sourceStage <= 3 ? 20 : 24, conveyorLaneCount);
            var original = main.Concat(branches.SelectMany(branch => branch.Groups)).ToArray();
            if (!overrideCakeSupply) return original;
            if (colorCount < 1 || colorCount > 9 || cakeCount < colorCount * 4 || cakeCount % 4 != 0)
                throw new InvalidOperationException("Cake Count must be a multiple of 4, with at least 4 cakes per color (1–9 colors).");
            var palette = original.Select(group => group.Color).Concat(new[] {
                BlockColorType.Red, BlockColorType.Green, BlockColorType.Blue, BlockColorType.Yellow,
                BlockColorType.Purple, BlockColorType.Orange, BlockColorType.Custom1,
                BlockColorType.Custom2, BlockColorType.Custom3 }).Distinct().Take(colorCount).ToArray();
            int rowsPerColorQuantum = 4 / conveyorLaneCount;
            int trayUnits = cakeCount / 4;
            main = palette.Select((color, index) => new StageGroupSpec(color,
                (trayUnits / colorCount + (index < trayUnits % colorCount ? 1 : 0)) * rowsPerColorQuantum)).ToArray();
            branches = branches.Select(branch => new StageBranchSpec(branch.Name, branch.MergeT,
                branch.ConnectFromLeft, Array.Empty<StageGroupSpec>(), branch.Knots)).ToArray();
            return main;
        }

        [Serializable]
        public struct MacaronBatch
        {
            public BlockColorType color;
            [Min(1)] public int count;
        }

        /// <summary>
        /// One prop (chute, slot marker, VFX, collider) bound to a conveyor opening.
        /// Positions are recomputed from the opening, so moving the gate moves the prop.
        /// </summary>
        [Serializable]
        public sealed class GateMount
        {
            public string label = "Chute";
            public bool enabled = true;

            [Tooltip("Index into ConveyorTrackMeshBuilder.openings.")]
            [Min(0)] public int gateIndex;

            [Tooltip("Spawned at every slot. Leave empty to create a bare empty anchor instead.")]
            public GameObject prefab;

            [Tooltip("How many props to place across this gate.")]
            [Min(1)] public int slotCount = 1;

            [Tooltip("Spread slots evenly across the gate length. Off = all at the gate centre.")]
            public bool spreadAlongGate = true;

            [Tooltip("Fixed gap between slots, in metres, measured along the belt. " +
                     "0 = derive the gap from the gate length.")]
            [Min(0f)] public float slotSpacing = 0f;

            [Tooltip("Offset in the mount's own space. +Z = further out through the gate, " +
                     "+Y = up, +X = along the belt.")]
            public Vector3 positionOffset;

            [Tooltip("Extra rotation applied after the prop is aimed out through the gate.")]
            public Vector3 rotationOffset;

            [Tooltip("Off = keep the prefab's own rotation, only move it into place.")]
            public bool alignToGate = true;
        }

        [Header("Macaron supply, first batch reaches the exit first")]
        public bool useCustomMacaronOrder;
        [Tooltip("Ordered color batches. Batches may cross row boundaries; set Count=1 to author individual cakes.")]
        public MacaronBatch[] macaronOrder = Array.Empty<MacaronBatch>();
        [TextArea] public string instruction;
        [Tooltip("Ordered conveyor spline. Closed tracks use two Feeder Branches and collect just before the seam at T=1.")]
        public SplineContainer conveyorPath;
        [Tooltip("Optional feeder branches for a closed main conveyor. Rows alternate in this list order; branch ends must meet the main spline.")]
        public ConveyorJunction[] feederBranches = Array.Empty<ConveyorJunction>();
        public ConveyorGateDoor collectionGate;
        [Header("Loop cake spacing")]
        [Tooltip("On: independent lane slots and near-equal cake spacing, like the reference video. Off: shared rows aligned before collection. Applied when the level starts.")]
        public bool independentLanePacking = true;
        [Tooltip("Multiplies automatic ring row spacing. Lower = closer cakes; very low values can overlap on inner bends. Applied when the level starts.")]
        [Range(.5f, 1.5f)] public float loopSpacingMultiplier = .9f;
        [Tooltip("Multiplies feeder row spacing, independently of the ring. Applied when the level starts.")]
        [Range(.5f, 1.5f)] public float feederSpacingMultiplier = .9f;
        [Header("Level layout")]
        public Transform trayRoot;
        public Transform[] waitingSlots = new Transform[6];
        public Transform counterAnchor;
        [Range(1, 5)] public int columns = 3;
        [Tooltip("Keep matching macarons together in the supply without changing the conveyor layout.")]
        public bool clusterColors = true;
        [Tooltip("Target pieces per color cluster. It rounds up to full conveyor rows using Columns.")]
        [Range(6, 24)] public int colorClusterSize = 12;
        [Tooltip("Shortest consecutive run of one macaron color, measured in conveyor rows.")]
        [Range(1, 10)] public int minColorRunRows = 1;
        [Tooltip("Longest consecutive run of one macaron color, measured in conveyor rows.")]
        [Range(1, 10)] public int maxColorRunRows = 10;
        [Tooltip("Maximum different colors introduced together. Three keeps one of the four starting tray slots free.")]
        [Range(1, 3)] public int activeColorLimit = 3;
        [Min(.22f)] public float laneSpacing = .25f;
        [Min(.24f)] public float rowSpacing = .32f;
        [Min(0)] public float stopBeforeExit = .5f;
        [Min(.1f)] public float exitZoneLength = 1.4f;
        [Range(55, 85)] public float cameraTilt = 72;
        [Range(20, 60)] public float cameraFieldOfView = 35;
        [Tooltip("Safe-area margins: left, right, bottom, top. Smaller margins make the board fill more of the screen.")]
        public Vector4 cameraPadding = new Vector4(.015f, .015f, .12f, .065f);

        [Header("Conveyor gates → chutes / slots")]
        [Tooltip("Leave empty to auto-resolve from Conveyor Path.")]
        public ConveyorTrackMeshBuilder conveyorTrack;
        [Tooltip("Parent for generated props. Leave empty and a child called 'Gate Mounts' is created.")]
        public Transform gateMountRoot;
        public GateMount[] gateMounts = Array.Empty<GateMount>();
        [Tooltip("Overwrite Waiting Slots with the first six generated props. " +
                 "Turn this on only if the gates really do define the waiting area.")]
        public bool bindWaitingSlotsToGates;

        public MacaronTray[] GetTrays() => trayRoot.GetComponentsInChildren<MacaronTray>(true);

        public void ArrangeTraysOnBoard()
        {
            var board = transform.Find("Tray board inset");
            var surface = board != null ? board.GetComponent<Renderer>() : null;
            var trays = GetTrays();
            if (surface == null || trays.Length == 0) return;
            var bounds = surface.bounds;
            var available = new Vector2(bounds.size.x - .3f, bounds.size.z - .3f);
            if (available.x <= 0 || available.y <= 0) return;
            float pyramidFit = 1;
            int lowestPyramidLayer = trays.Min(tray => tray.stackLayer);
            int highestPyramidLayer = trays.Max(tray => tray.stackLayer);
            if (trayLayoutStyle == TrayLayoutStyle.Pyramid)
                foreach (var layer in trays.GroupBy(tray => tray.stackLayer))
                {
                    var sizes = layer.Select(tray => Vector3.Scale(tray.GetComponent<BoxCollider>().size,
                        tray.transform.lossyScale)).Select(size => new Vector2(size.x, size.z)).ToArray();
                    var poses = PackTrayLayer(sizes, layer.Key, TrayLayoutStyle.Rectangle, trayArrangementSeed);
                    pyramidFit = Mathf.Min(pyramidFit, available.x / (poses.Max(p => p.xMax) - poses.Min(p => p.xMin)),
                        available.y / (poses.Max(p => p.yMax) - poses.Min(p => p.yMin)));
                }
            foreach (var layer in trays.GroupBy(tray => tray.stackLayer))
            {
                var group = layer.ToArray();
                var sizes = group.Select(tray => Vector3.Scale(tray.GetComponent<BoxCollider>().size,
                    tray.transform.lossyScale)).Select(size => new Vector2(size.x, size.z)).ToArray();
                var poses = PackTrayLayer(sizes, layer.Key, trayLayoutStyle == TrayLayoutStyle.Pyramid ? TrayLayoutStyle.Rectangle : trayLayoutStyle, trayArrangementSeed);
                float width = poses.Max(p => p.xMax) - poses.Min(p => p.xMin);
                float depth = poses.Max(p => p.yMax) - poses.Min(p => p.yMin);
                float tierProgress = highestPyramidLayer == lowestPyramidLayer ? 0
                    : Mathf.InverseLerp(lowestPyramidLayer, highestPyramidLayer, layer.Key);
                float fit = trayLayoutStyle == TrayLayoutStyle.Pyramid ? pyramidFit * Mathf.Lerp(1f, .9f, tierProgress)
                    : Mathf.Min(1, available.x / width, available.y / depth);
                for (int i = 0; i < group.Length; i++)
                {
                    var tray = group[i];
                    bool turned = Mathf.Abs(poses[i].width - sizes[i].y) < .001f;
                    tray.transform.rotation = Quaternion.Euler(0, turned ? 90 : 0, 0);
                    tray.transform.localScale *= fit;
                    var center = tray.transform.TransformPoint(tray.GetComponent<BoxCollider>().center);
                    tray.transform.position += new Vector3(bounds.center.x + poses[i].center.x * fit - center.x,
                        0, bounds.center.z + poses[i].center.y * fit - center.z);
                }
            }
        }

        public static Rect[] PackTrayLayer(Vector2[] sizes, int layer, TrayLayoutStyle style = TrayLayoutStyle.Compact, int seed = 0)
        {
            if (sizes == null) throw new ArgumentNullException(nameof(sizes));
            if (!Enum.IsDefined(typeof(TrayLayoutStyle), style)) throw new ArgumentOutOfRangeException(nameof(style));
            foreach (var size in sizes)
                if (size.x <= 0 || size.y <= 0 || !float.IsFinite(size.x + size.y))
                    throw new ArgumentException("Tray footprints must be finite and positive.");
            if (sizes.Length == 0) return Array.Empty<Rect>();
            var placed = style == TrayLayoutStyle.Compact ? new List<Rect>() : ShapeTrayLayer(sizes, style, layer, seed).ToList();
            // ponytail: greedy edge packing is for dozens of trays per layer; use a bin packer for hundreds.
            for (int i = 0; style == TrayLayoutStyle.Compact && i < sizes.Length; i++)
            {
                float bestScore = float.PositiveInfinity;
                Rect best = default;
                for (int turn = 0; turn < 2; turn++)
                {
                    var size = turn == 0 ? sizes[i] : new Vector2(sizes[i].y, sizes[i].x);
                    var candidates = new List<Vector2> { -size * .5f };
                    float gap = Mathf.Min(size.x, size.y) * .045f;
                    foreach (var other in placed)
                        for (int align = 0; align < 3; align++)
                        {
                            float x = Mathf.Lerp(other.xMin, other.xMax - size.x, align * .5f);
                            float z = Mathf.Lerp(other.yMin, other.yMax - size.y, align * .5f);
                            candidates.Add(new Vector2(other.xMax + gap, z));
                            candidates.Add(new Vector2(other.xMin - gap - size.x, z));
                            candidates.Add(new Vector2(x, other.yMax + gap));
                            candidates.Add(new Vector2(x, other.yMin - gap - size.y));
                        }
                    foreach (var position in candidates)
                    {
                        var rect = new Rect(position, size);
                        var padded = new Rect(position - Vector2.one * (gap * .49f), size + Vector2.one * (gap * .98f));
                        if (placed.Any(other => padded.Overlaps(other))) continue;
                        float radiusX = Mathf.Max(Mathf.Abs(rect.xMin), Mathf.Abs(rect.xMax));
                        float radiusZ = Mathf.Max(Mathf.Abs(rect.yMin), Mathf.Abs(rect.yMax));
                        float score = radiusX * radiusX + radiusZ * radiusZ + rect.center.sqrMagnitude * .1f;
                        if (turn != (i + layer) % 2) score += sizes[i].sqrMagnitude * .03f;
                        if (score >= bestScore) continue;
                        bestScore = score;
                        best = rect;
                    }
                }
                placed.Add(best);
            }
            var center = new Vector2((placed.Min(p => p.xMin) + placed.Max(p => p.xMax)) * .5f,
                (placed.Min(p => p.yMin) + placed.Max(p => p.yMax)) * .5f);
            return placed.Select(rect => new Rect(rect.position - center, rect.size)).ToArray();
        }

        private static Rect[] ShapeTrayLayer(Vector2[] sizes, TrayLayoutStyle style, int layer, int seed)
        {
            int count = sizes.Length;
            var random = new System.Random(unchecked(seed ^ layer * 486187739 ^ (int)style * 16777619));
            bool firstVertical = false;
            var trays = sizes.Select((size, index) =>
            {
                bool vertical = random.NextDouble() < .5;
                if (index == 0) firstVertical = vertical;
                if (index == count - 1 && count > 1 && vertical == firstVertical) vertical = !vertical;
                float longSide = Mathf.Max(size.x, size.y), shortSide = Mathf.Min(size.x, size.y);
                return vertical ? new Vector2(shortSide, longSide) : new Vector2(longSide, shortSide);
            }).ToArray();
            float longSide = trays.Max(size => Mathf.Max(size.x, size.y));
            float shortSide = trays.Max(size => Mathf.Min(size.x, size.y));
            float gap = shortSide * .18f;
            int rows;
            if (style == TrayLayoutStyle.Pyramid)
            {
                int maxRows = Mathf.CeilToInt(Mathf.Sqrt(count));
                rows = Enumerable.Range(1, maxRows)
                    .Where(row => count - (row - 1) * (row - 1) <= 2 * row + 1)
                    .OrderBy(row => Mathf.Abs(Mathf.Log((count - (row - 1) * (row - 1)) / (float)(2 * row - 1))))
                    .First();
            }
            else
            {
                rows = Enumerable.Range(1, count).OrderBy(row =>
                    Mathf.Abs(Mathf.Log(Mathf.Ceil(count / (float)row) * longSide / (row * shortSide))) +
                    2 * (Mathf.Ceil(count / (float)row) * row - count) / count).First();
                if (style == TrayLayoutStyle.Diamond)
                    rows = Mathf.Clamp(2 * Mathf.RoundToInt((Mathf.Sqrt(2 * count * longSide / shortSide) - 1) * .5f) + 1, 1, count);
            }
            var weights = Enumerable.Range(0, rows).Select(row => style == TrayLayoutStyle.Diamond
                ? 1f + Mathf.Min(row, rows - 1 - row)
                : 1f).ToArray();
            float totalWeight = weights.Sum();
            var lengths = weights.Select(weight => Mathf.FloorToInt(count * weight / totalWeight)).ToArray();
            var middleFirst = Enumerable.Range(0, rows).OrderBy(row => Mathf.Abs(row - (rows - 1) * .5f)).ToArray();
            int remaining = count - lengths.Sum();
            if (rows % 2 != 0 && remaining % 2 != 0) { lengths[rows / 2]++; remaining--; }
            foreach (int row in middleFirst.Where(row => rows % 2 == 0 || row != rows / 2).Take(remaining)) lengths[row]++;

            var rowDepths = new float[rows];
            int trayIndex = 0;
            for (int row = 0; row < rows; row++)
                for (int column = 0; column < lengths[row]; column++, trayIndex++)
                    rowDepths[row] = Mathf.Max(rowDepths[row], trays[trayIndex].y);
            float depth = rowDepths.Sum() + gap * (rows - 1);
            var result = new Rect[count];
            float z = depth * .5f;

            for (int row = 0; row < rows; row++)
            {
                z -= rowDepths[row] * .5f;
                trayIndex = lengths.Take(row).Sum();
                float width = 0;
                for (int column = 0; column < lengths[row]; column++) width += trays[trayIndex + column].x;
                width += gap * (lengths[row] - 1);
                float x = -width * .5f;
                for (int column = 0; column < lengths[row]; column++)
                {
                    var size = trays[trayIndex];
                    x += size.x * .5f;
                    var center = new Vector2(x, z) + new Vector2((float)(random.NextDouble() - .5) * gap * .9f,
                        (float)(random.NextDouble() - .5) * gap * .9f);
                    result[trayIndex] = new Rect(center - size * .5f, size);
                    x += size.x * .5f + gap;
                    trayIndex++;
                }
                z -= rowDepths[row] * .5f + gap;
            }
            return result;
        }
        public void MoveRemainingBadgeToTraySide()
        {
            if (waitingSlots == null || waitingSlots.Length == 0 || Array.Exists(waitingSlots, slot => slot == null)) return;
            var badge = transform.Find("Remaining badge");
            if (badge == null) return;
            float left = waitingSlots.Min(slot => transform.InverseTransformPoint(slot.position).x);
            float front = waitingSlots.Max(slot => transform.InverseTransformPoint(slot.position).z);
            var position = badge.localPosition;
            position.x = left - badge.localScale.x * .45f;
            position.z = front + 1.1f;
            badge.localPosition = position;
        }

        // ─────────────────────────────────────────────────────────────────────
        //  Gate mounts
        // ─────────────────────────────────────────────────────────────────────

        /// <summary>Resolves the mesh builder, falling back to the component on the conveyor spline.</summary>
        public ConveyorTrackMeshBuilder ResolveTrack()
        {
            if (conveyorTrack != null) return conveyorTrack;
            if (conveyorPath != null) conveyorTrack = conveyorPath.GetComponent<ConveyorTrackMeshBuilder>();
            if (conveyorTrack == null) conveyorTrack = GetComponentInChildren<ConveyorTrackMeshBuilder>(true);
            return conveyorTrack;
        }

        /// <summary>
        /// Rebuilds every prop bound to a conveyor opening. Safe to call repeatedly —
        /// previously generated props are removed first, hand-placed children are left alone.
        /// </summary>
        [ContextMenu("Sync Gate Mounts")]
        public void SyncGateMounts()
        {
            var track = ResolveTrack();
            if (track == null)
                throw new InvalidOperationException($"{name}: no ConveyorTrackMeshBuilder to read openings from.");

            Transform root = EnsureGateMountRoot();
            ClearGeneratedMounts(root);

            if (gateMounts == null || gateMounts.Length == 0) return;

            var created = new List<Transform>();

            for (int m = 0; m < gateMounts.Length; m++)
            {
                var mount = gateMounts[m];
                if (mount == null || !mount.enabled) continue;

                if (mount.gateIndex < 0 || mount.gateIndex >= track.OpeningCount)
                    throw new InvalidOperationException(
                        $"{name}: gate mount '{mount.label}' points at opening {mount.gateIndex}, " +
                        $"but the track only has {track.OpeningCount}.");

                int count = Mathf.Max(1, mount.slotCount);
                float gateLength = track.GetOpeningLength(mount.gateIndex);

                for (int i = 0; i < count; i++)
                {
                    // Where along the gate this slot sits.
                    float u = count == 1 || !mount.spreadAlongGate
                        ? .5f
                        : (i + .5f) / count;

                    if (!track.TryGetOpeningPose(mount.gateIndex, u,
                            out Vector3 position, out Quaternion rotation, out Vector3 beltForward))
                        continue;

                    // A fixed spacing overrides the even spread: lay the slots out
                    // symmetrically around the gate centre instead.
                    if (mount.spreadAlongGate && mount.slotSpacing > 0f && count > 1)
                    {
                        track.TryGetOpeningPose(mount.gateIndex, .5f,
                            out position, out rotation, out beltForward);
                        float offset = (i - (count - 1) * .5f) * mount.slotSpacing;
                        position += beltForward * offset;

                        float half = gateLength * .5f;
                        if (Mathf.Abs(offset) > half + .0001f)
                            Debug.LogWarning($"{name}: gate mount '{mount.label}' slot {i} " +
                                             $"sits {Mathf.Abs(offset):0.###} m from the centre but the gate is " +
                                             $"only {gateLength:0.###} m long.", this);
                    }

                    var go = Spawn(mount, root);
                    var marker = go.GetComponent<GeneratedGateMount>();
                    if (marker == null) marker = go.AddComponent<GeneratedGateMount>();
                    marker.gateIndex = mount.gateIndex;
                    marker.slotIndex = i;

                    go.name = count == 1
                        ? $"{mount.label} (gate {mount.gateIndex})"
                        : $"{mount.label} (gate {mount.gateIndex}) #{i}";

                    if (mount.alignToGate) go.transform.rotation = rotation * Quaternion.Euler(mount.rotationOffset);
                    go.transform.position = position + go.transform.rotation * mount.positionOffset;

                    created.Add(go.transform);
                }
            }

            if (!bindWaitingSlotsToGates) return;
            if (created.Count < 6)
            {
                Debug.LogWarning($"{name}: Bind Waiting Slots To Gates is on but only {created.Count} " +
                                 "props were generated; six are required. Waiting Slots left untouched.", this);
                return;
            }
            waitingSlots = created.Take(6).ToArray();
        }

        [ContextMenu("Clear Gate Mounts")]
        public void ClearGateMounts()
        {
            if (gateMountRoot != null) ClearGeneratedMounts(gateMountRoot);
        }

        private Transform EnsureGateMountRoot()
        {
            if (gateMountRoot != null) return gateMountRoot;

            var existing = transform.Find("Gate Mounts");
            if (existing != null) { gateMountRoot = existing; return gateMountRoot; }

            var go = new GameObject("Gate Mounts");
            go.transform.SetParent(transform, false);
#if UNITY_EDITOR
            if (!Application.isPlaying) UnityEditor.Undo.RegisterCreatedObjectUndo(go, "Create Gate Mount Root");
#endif
            gateMountRoot = go.transform;
            return gateMountRoot;
        }

        private static void ClearGeneratedMounts(Transform root)
        {
            var stale = root.GetComponentsInChildren<GeneratedGateMount>(true);
            foreach (var marker in stale)
            {
                if (marker == null) continue;
                var go = marker.gameObject;
                if (Application.isPlaying) Destroy(go);
#if UNITY_EDITOR
                else UnityEditor.Undo.DestroyObjectImmediate(go);
#else
                else DestroyImmediate(go);
#endif
            }
        }

        private static GameObject Spawn(GateMount mount, Transform parent)
        {
            GameObject go;
            if (mount.prefab == null)
            {
                go = new GameObject(mount.label);
            }
            else
            {
#if UNITY_EDITOR
                // The parent overload keeps the instance in the right scene / prefab stage.
                go = Application.isPlaying
                    ? Instantiate(mount.prefab, parent)
                    : (GameObject)UnityEditor.PrefabUtility.InstantiatePrefab(mount.prefab, parent);
#else
                go = Instantiate(mount.prefab, parent);
#endif
            }

            if (go.transform.parent != parent) go.transform.SetParent(parent, true);
#if UNITY_EDITOR
            if (!Application.isPlaying) UnityEditor.Undo.RegisterCreatedObjectUndo(go, "Create Gate Mount");
#endif
            return go;
        }

        // ─────────────────────────────────────────────────────────────────────
        //  Existing layout helpers
        // ─────────────────────────────────────────────────────────────────────

        public List<BlockColorType> BuildMacaronOrder()
        {
            var trays = GetTrays();
            if (!useCustomMacaronOrder)
            {
                var defaultSupplyOrder = trays.OrderByDescending(tray => tray.stackLayer)
                    .SelectMany(tray => Enumerable.Repeat(tray.levelColor, tray.Capacity)).ToList();
                return clusterColors ? ClusterColors(defaultSupplyOrder, colorClusterSize, columns, activeColorLimit,
                    minColorRunRows, maxColorRunRows) : defaultSupplyOrder;
            }
            if (macaronOrder == null || macaronOrder.Length == 0)
                throw new InvalidOperationException($"{name}: custom Macaron Order is empty.");
            var capacity = new int[7];
            var supply = new int[7];
            foreach (var tray in trays)
            {
                int color = (int)tray.levelColor;
                if (color < 1 || color > 6) throw new InvalidOperationException($"{name}: unsupported tray color {tray.levelColor}.");
                capacity[color] = checked(capacity[color] + tray.Capacity);
            }
            for (int i = 0; i < macaronOrder.Length; i++)
            {
                var batch = macaronOrder[i];
                int color = (int)batch.color;
                if (color < 1 || color > 6 || batch.count < 1)
                    throw new InvalidOperationException($"{name}: batch {i + 1} needs a supported color and Count >= 1.");
                if (batch.count > capacity[color] - supply[color])
                    throw new InvalidOperationException($"{name}: batch {i + 1} exceeds tray capacity for {batch.color} ({capacity[color]}).");
                supply[color] += batch.count;
            }
            for (int color = 1; color <= 6; color++)
                if (supply[color] != capacity[color])
                    throw new InvalidOperationException($"{name}: {(BlockColorType)color} has {supply[color]} cakes but {capacity[color]} tray pockets.");
            return macaronOrder.SelectMany(batch => Enumerable.Repeat(batch.color, batch.count)).ToList();
        }

        public static List<BlockColorType> ClusterColors(List<BlockColorType> supply, int size, int columns, int activeColors,
            int minRows = 1, int maxRows = 10)
        {
            int rowWidth = Mathf.Max(1, columns);
            int minimum = Mathf.Clamp(Mathf.Min(minRows, maxRows), 1, 10);
            int maximum = Mathf.Clamp(Mathf.Max(minRows, maxRows), minimum, 10);
            var remaining = supply.GroupBy(color => color).ToDictionary(group => group.Key, group => group.Count());
            var colors = supply.Distinct().ToArray();
            var result = new List<BlockColorType>(supply.Count);
            int paletteSize = Mathf.Clamp(activeColors, 1, 3);
            int seed = size;
            foreach (var color in supply) seed = seed * 31 + (int)color;
            var random = new System.Random(seed);
            for (int start = 0; start < colors.Length; start += paletteSize)
            {
                int end = Mathf.Min(start + paletteSize, colors.Length);
                while (Enumerable.Range(start, end - start).Any(index => remaining[colors[index]] > 0))
                    for (int index = start; index < end; index++)
                    {
                        var color = colors[index];
                        int take = Mathf.Min(random.Next(minimum, maximum + 1) * rowWidth, remaining[color]);
                        for (int i = 0; i < take; i++) result.Add(color);
                        remaining[color] -= take;
                    }
            }
            return result;
        }

        public static (int[] feeder, int[] index) BuildFeederAssignments(IReadOnlyList<BlockColorType> supply,
            int columns, int seededRows, int feederCount)
        {
            int rowCount = Mathf.CeilToInt(supply.Count / (float)Mathf.Max(1, columns));
            var feeder = Enumerable.Repeat(-1, rowCount).ToArray();
            var index = Enumerable.Repeat(-1, rowCount).ToArray();
            if (feederCount <= 0) return (feeder, index);

            var queued = new int[feederCount];
            int currentFeeder = 0;
            bool hasPrevious = false;
            BlockColorType previous = default;
            for (int row = Mathf.Clamp(seededRows, 0, rowCount); row < rowCount; row++)
            {
                var color = supply[row * columns];
                if (hasPrevious && color != previous) currentFeeder = (currentFeeder + 1) % feederCount;
                feeder[row] = currentFeeder;
                index[row] = queued[currentFeeder]++;
                previous = color;
                hasPrevious = true;
            }
            return (feeder, index);
        }

        public void AlignExitToWaitingSlots()
        {
            if (conveyorPath != null && conveyorPath.Spline.Closed) return;
            // When the waiting area is derived from the gates, the gates own the layout —
            // shifting the spline here would fight the sync pass.
            if (bindWaitingSlotsToGates) return;

            if (conveyorPath == null || waitingSlots == null || waitingSlots.Length == 0 ||
                Array.Exists(waitingSlots, slot => slot == null) || conveyorPath.Spline.Count < 2) return;
            Vector3 center = Vector3.zero;
            foreach (var slot in waitingSlots) center += transform.InverseTransformPoint(slot.position);
            center /= waitingSlots.Length;
            var spline = conveyorPath.Spline;
            Vector3 end = transform.InverseTransformPoint(conveyorPath.transform.TransformPoint((Vector3)spline[spline.Count - 1].Position));
            Vector3 shift = conveyorPath.transform.InverseTransformVector(transform.TransformVector(Vector3.right * (center.x - end.x)));
            if (shift.sqrMagnitude < .00000001f) return;
            // Move the exit bend with its endpoint so the rounded inner wall keeps its radius.
            int first = spline.Count >= 4 ? spline.Count - 3 : spline.Count - 1;
            for (int i = first; i < spline.Count; i++)
            {
                var knot = spline[i];
                knot.Position += (Unity.Mathematics.float3)shift;
                spline[i] = knot;
            }
        }

        public void ValidateLayout()
        {
            if (conveyorPath == null || conveyorPath.Spline.Count < 2 ||
                trayRoot == null || GetTrays().Length == 0 || waitingSlots == null || waitingSlots.Length != 6 ||
                Array.Exists(waitingSlots, slot => slot == null) || counterAnchor == null)
                throw new InvalidOperationException($"{name}: assign a conveyor, trays, six waiting slots and counter anchor.");
            if (conveyorPath.Spline.Closed && (feederBranches == null ||
                Array.Exists(feederBranches, branch => branch == null || branch.mainTrack != conveyorPath.GetComponent<ConveyorTrackMeshBuilder>() ||
                    branch.joinAt != ConveyorJunction.BranchEnd.End || branch.GetComponent<SplineContainer>().Spline.Closed)))
                throw new InvalidOperationException($"{name}: a closed conveyor requires open feeder branches joined to this track at their ends.");
            if (conveyorLaneCount != 2 && conveyorLaneCount != 4)
                throw new InvalidOperationException($"{name}: Conveyor Lane Count must be 2 or 4.");
            if (columns < 1 || columns > 5) throw new InvalidOperationException($"{name}: Columns must be between 1 and 5.");
            if (activeColorLimit < 1 || activeColorLimit > 3)
                throw new InvalidOperationException($"{name}: Active Color Limit must be between 1 and 3.");
            if (Array.Exists(GetTrays(), tray => tray.pockets == null || tray.pockets.Length < 4 || tray.pockets.Length > 8 ||
                Array.Exists(tray.pockets, pocket => pocket == null) || tray.lid == null || tray.GetComponent<BoxCollider>() == null))
                throw new InvalidOperationException($"{name}: each tray needs 4–8 assigned pockets, a lid and a BoxCollider.");
            ValidateGateMounts();
            if (useCustomMacaronOrder) BuildMacaronOrder();
        }

        private void ValidateGateMounts()
        {
            if (gateMounts == null || gateMounts.Length == 0) return;

            var track = ResolveTrack();
            if (track == null)
                throw new InvalidOperationException($"{name}: gate mounts are configured but no ConveyorTrackMeshBuilder was found.");

            for (int i = 0; i < gateMounts.Length; i++)
            {
                var mount = gateMounts[i];
                if (mount == null || !mount.enabled) continue;
                if (mount.gateIndex < 0 || mount.gateIndex >= track.OpeningCount)
                    throw new InvalidOperationException(
                        $"{name}: gate mount {i + 1} ('{mount.label}') targets opening {mount.gateIndex}, " +
                        $"but the track has {track.OpeningCount}.");
                if (mount.slotCount < 1)
                    throw new InvalidOperationException($"{name}: gate mount {i + 1} needs Slot Count >= 1.");
            }
        }
    }
}
